from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def _format_probability(value):
    try:
        return f"{float(value) * 100:.2f} %"
    except (TypeError, ValueError):
        return "--"


def _format_datetime(value):
    if not value:
        return "--"

    if hasattr(value, "strftime"):
        return value.strftime("%d-%m-%Y %I:%M %p")

    return str(value)


def generate_report(report_data=None, filename=None):
    report_data = report_data or {}
    patient_name = report_data.get("patient_name") or "Patient"
    age = report_data.get("age") or "--"
    prediction = report_data.get("prediction")

    target = filename or BytesIO()

    doc = SimpleDocTemplate(
        target,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title="Healthcare Prediction Report",
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Title"],
        textColor=colors.HexColor("#0d6efd"),
        fontSize=22,
        leading=28,
        spaceAfter=16,
    ))
    styles.add(ParagraphStyle(
        name="SectionTitle",
        parent=styles["Heading2"],
        textColor=colors.HexColor("#1f2937"),
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="BodyTextClean",
        parent=styles["BodyText"],
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#374151"),
    ))

    elements = [
        Paragraph("Healthcare Prediction Report", styles["ReportTitle"]),
        Paragraph(
            "Generated by the Healthcare AI Prediction System.",
            styles["BodyTextClean"],
        ),
        Spacer(1, 14),
    ]

    if prediction:
        table_data = [
            ["Patient Name", patient_name],
            ["Age", age],
            ["Disease", prediction.get("disease") or "--"],
            ["Prediction Result", prediction.get("result") or "--"],
            ["Probability", _format_probability(prediction.get("probability"))],
            ["Generated On", _format_datetime(prediction.get("created_at"))],
        ]
    else:
        table_data = [
            ["Patient Name", patient_name],
            ["Age", age],
            ["Prediction Result", "No prediction record found"],
            ["Next Step", "Run a disease prediction first, then generate the report."],
        ]

    summary_table = Table(table_data, colWidths=[1.9 * inch, 4.3 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e7f1ff")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#084298")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10.5),
        ("LEADING", (0, 0), (-1, -1), 14),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(summary_table)

    elements.extend([
        Paragraph("Health Suggestions", styles["SectionTitle"]),
        Paragraph(
            "Maintain a balanced diet, exercise regularly, drink enough water, "
            "sleep well, and schedule regular health check-ups.",
            styles["BodyTextClean"],
        ),
        Paragraph("Important Note", styles["SectionTitle"]),
        Paragraph(
            "This report is generated for educational project use only. It is not "
            "a medical diagnosis and should not replace advice from a qualified "
            "healthcare professional.",
            styles["BodyTextClean"],
        ),
    ])

    doc.build(elements)

    if hasattr(target, "seek"):
        target.seek(0)

    return target
